In [8]:
import numpy as np

Helper function to normalize a vector to make it probability distribution

In [15]:
def normalize(vec):
    """Multiply each number by a constant such that the sum is 1.0"""
    alpha = 1/(sum(vec))
    return alpha * vec

In [18]:
# Define state transition matrix
#Excluding the row corresponding to START state and column corresponding to STOP state
T = np.array([[0.3,0.2,0.1,0.1],[0.25,0.1,0.05,0.15],[0.05,0.4,0.15,0.2],[0.5,0.2,0.2,0.05]])
print(T)

[[0.3  0.2  0.1  0.1 ]
 [0.25 0.1  0.05 0.15]
 [0.05 0.4  0.15 0.2 ]
 [0.5  0.2  0.2  0.05]]


# Q7a. Calculation of $$\mathbf{P}(X_1|E_1)$$



In [14]:
#Hadaramrd product or elementwise product of two vectors
PX1gX0 = np.array([1,0,0,0])
PE1gX1 = np.array([0.6,0.1,0.2,0.3])
#Hadamard or element-wise product of these two vectors
PX1gE1_unnormalized = PX1gX0 * PE1gX1
print(PX1gE1_unnormalized)
PX1gE1 = normalize(PX1gE1_unnormalized)
print(PX1gE1)

[0.6 0.  0.  0. ]
[1. 0. 0. 0.]


# Q7b Calculation of $$\mathbf{P}(X_2|E_1,E_2)$$

In [16]:
#Get f11 from Q7a
f11 = PX1gE1
#Obserbvation matrix at t=2
O2 = np.diag([0.2,0.5,0.1,0.4])
print(O2)

[[0.2 0.  0.  0. ]
 [0.  0.5 0.  0. ]
 [0.  0.  0.1 0. ]
 [0.  0.  0.  0.4]]


In [21]:
f12 = normalize(np.matmul(O2, np.matmul(T.T,f11)))
print(f12)

[0.28571429 0.47619048 0.04761905 0.19047619]


# Q7c Calculation of $$\mathbf{P}(X_3|E_1,E_2, E_3)$$

In [22]:
# Observation matrix at t = 3
O3 = np.diag([0.2,0.4,0.7,0.3])
print(O3)

[[0.2 0.  0.  0. ]
 [0.  0.4 0.  0. ]
 [0.  0.  0.7 0. ]
 [0.  0.  0.  0.3]]


In [24]:
f13 = normalize(np.matmul(O3, np.matmul(T.T,f12)))
print(f13)

[0.26375909 0.28245067 0.298027   0.15576324]
