# Introduction to PyTorch  

## PyTorch

PyTorch is an open-source machine learning library developed by Facebook's AI Research lab. It provides a flexible platform for developing deep learning models due to its dynamic computation graph, which allows for more intuitive and flexible model building and debugging.

## Similarities to NumPy:

- Tensor Operations: PyTorch's core data structure is the tensor and it is similar to NumPy's ndarray. Tensors in PyTorch support the same operations as NumPy arrays.

- Interoperability: PyTorch tensors can easily be converted to NumPy arrays and vice versa, facilitating the use of both libraries 

- Numerical Computation: Both libraries are designed for numerical computations such as addition, multiplication, and linear algebra operations.

## Differences from NumPy:

- Autograd: PyTorch has an automatic differentiation library called Autograd, which automatically computes gradients, allowing for easy implementation of backpropagation. This feature is not present in NumPy.

- GPU Support PyTorch natively supports operations on GPUs, enabling faster computation for large-scale machine learning tasks. NumPy primarily operates on CPUs, although it can be integrated with libraries like CuPy for GPU support.

    

    


In [176]:
import torch

# Creating PyTorch Tensors

  - scalar  
  - Vector
  - Matrix

## Create a scalar tensor 

In [177]:
scalar_tensor = torch.tensor([3.5])

print(f"scalar_tensor: {scalar_tensor}")
print(f"Type of scalar_tensor: {scalar_tensor.type()}")
print(f"Dimensions of scalar_tensor: {scalar_tensor.dim()}")
print(f"Size of scalar_tensor: {scalar_tensor.size()}")


scalar_tensor: tensor([3.5000])
Type of scalar_tensor: torch.FloatTensor
Dimensions of scalar_tensor: 1
Size of scalar_tensor: torch.Size([1])


### Extract the scalar from scalar tensor
    - we need this extraction while working with loss functions, where loss is the scalar value and is stored in a tensor

In [178]:
#we cannot do the following; it gives us a tensor
scalar_ = scalar_tensor[0]
print(f"Type of scalar: {scalar_.type()}")
print(f"Type of scalar: {scalar_.dim()}")

# Use .item() to extract scalar
scalar = scalar_tensor.item()
print(f"Type of scalar: {type(scalar)}")

Type of scalar: torch.FloatTensor
Type of scalar: 0
Type of scalar: <class 'float'>


## Create a vector tensor 

In [179]:
vector_tensor = torch.tensor([3.5, 1.4, 2.5, 3.6])
#vector_tensor = torch.tensor([3, 1, 2, 3])
print(f"Vector Tensor: {vector_tensor}")
print(f"Type of vector_tensor: {vector_tensor.type()}")
print(f"Dimensions of vector_tensor: {vector_tensor.dim()}")
print(f"Size of vector_tensor: {vector_tensor.size()}")

Vector Tensor: tensor([3.5000, 1.4000, 2.5000, 3.6000])
Type of vector_tensor: torch.FloatTensor
Dimensions of vector_tensor: 1
Size of vector_tensor: torch.Size([4])


## Create a two dimensional matrix tensor 

In [180]:
matrix_tensor = torch.tensor([[3.5, 1.4],[2.5, 3.6]])
#vector_tensor = torch.tensor([3, 1, 2, 3])
print(f"Vector Tensor: {matrix_tensor}")
print(f"Type of matrix_tensor: {matrix_tensor.type()}")
print(f"Dimensions of matrix_tensor: {matrix_tensor.dim()}")
print(f"Size of matrix_tensor: {matrix_tensor.size()}")

Vector Tensor: tensor([[3.5000, 1.4000],
        [2.5000, 3.6000]])
Type of matrix_tensor: torch.FloatTensor
Dimensions of matrix_tensor: 2
Size of matrix_tensor: torch.Size([2, 2])


## Create a three dimensional matrix tensor 

In [181]:
matrix_tensor = torch.tensor([[[3.5, 1.4],[2.5, 3.6]],[[0.1,3.2],[1.3,8.9]]])
#vector_tensor = torch.tensor([3, 1, 2, 3])
print(f"Vector Tensor: {matrix_tensor}")
print(f"Type of matrix_tensor: {matrix_tensor.type()}")
print(f"Dimensions of matrix_tensor: {matrix_tensor.dim()}")
print(f"Size of matrix_tensor: {matrix_tensor.size()}")

Vector Tensor: tensor([[[3.5000, 1.4000],
         [2.5000, 3.6000]],

        [[0.1000, 3.2000],
         [1.3000, 8.9000]]])
Type of matrix_tensor: torch.FloatTensor
Dimensions of matrix_tensor: 3
Size of matrix_tensor: torch.Size([2, 2, 2])


# Arithmetic with tensors

In [182]:
X = torch.tensor([[3.5, 1.4],[2.5, 3.6]])
print("Tensor X: ")
print(X)
#broadcasting with scalar addition
print('Adding a scalar 2 to tensor X: ')
X_1 = 2+X
print(X_1)
# Tensor Addition
print('Tensor Y')
Y = torch.tensor([[1.0, 0],[0, 1]])
print(Y)
print('Sum of Tensors X and Y')
tensor_sum = X +Y  
print(tensor_sum)
print('Multiplication of Tensors X and Y')
# Tensor Multiplication
tensor_mult = X @ Y
#You can also use torch.mm()
#tensor_mult = torch.mm(X, Y)
print(tensor_mult)
print('Elementwise Multiplication of Tensors X and Y')
tensor_elementwise_mult = X * Y  
print(tensor_elementwise_mult)

Tensor X: 
tensor([[3.5000, 1.4000],
        [2.5000, 3.6000]])
Adding a scalar 2 to tensor X: 
tensor([[5.5000, 3.4000],
        [4.5000, 5.6000]])
Tensor Y
tensor([[1., 0.],
        [0., 1.]])
Sum of Tensors X and Y
tensor([[4.5000, 1.4000],
        [2.5000, 4.6000]])
Multiplication of Tensors X and Y
tensor([[3.5000, 1.4000],
        [2.5000, 3.6000]])
Elementwise Multiplication of Tensors X and Y
tensor([[3.5000, 0.0000],
        [0.0000, 3.6000]])


# Creating a special matrices such as random, zeros, ones, etc.

In [183]:
X_rand =torch.rand(2,5,3)
print(X_rand)

tensor([[[0.9327, 0.1867, 0.0419],
         [0.2798, 0.2469, 0.6317],
         [0.9485, 0.3020, 0.0346],
         [0.5483, 0.7159, 0.4256],
         [0.8861, 0.4769, 0.8366]],

        [[0.4816, 0.5795, 0.7640],
         [0.0011, 0.0186, 0.4553],
         [0.5409, 0.0301, 0.6940],
         [0.8266, 0.5475, 0.4417],
         [0.9350, 0.3886, 0.0259]]])


In [184]:
X_zeros=torch.zeros(2,5,3)
print(X_zeros)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [185]:
X_ones=torch.ones(2,5,3)
print(X_ones)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


## Datatypes in Tensors

### Floats versus integers

In [186]:
tensor = torch.tensor([1.5, 2.5, 3.5])
print(tensor.dtype) 

torch.float32


In [187]:
# Create a tensor with integer data type
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
print(int_tensor.dtype)  # Output: torch.int32

# Create a tensor with double (float64) data type
double_tensor = torch.tensor([1.5, 2.5, 3.5], dtype=torch.float64)
print(double_tensor.dtype)  # Output: torch.float64

torch.int32
torch.float64


In [188]:
# Convert to float
float_tensor = int_tensor.float()
print(float_tensor.dtype)  # Output: torch.float32

# Convert to int
int_tensor_again = float_tensor.int()
print(int_tensor_again.dtype)  # Output: torch.int32

# .to() to specify data type 
converted_tensor = tensor.to(torch.int64)
print(converted_tensor.dtype)  # Output: torch.int64

torch.float32
torch.int32
torch.int64


In [189]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [190]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [191]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [192]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


## Miscellaneous functions

In [193]:
x=torch.arange(10)
print(x)
print(x.type())


# Iterate over the tensor
for element in x:
    print(element)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor
tensor(0)
tensor(1)
tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor(6)
tensor(7)
tensor(8)
tensor(9)


In [194]:
x=torch.arange(10).long()
print(x)
print(x.type())
# Iterate over the tensor
for element in x:
    print(element)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor
tensor(0)
tensor(1)
tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor(6)
tensor(7)
tensor(8)
tensor(9)


In [195]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([9, 3, 5, 7, 1, 2, 4, 8, 6, 0])
torch.LongTensor


### Reshaping a tensor

In [196]:
x=torch.arange(8)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [197]:
print(x.view(4,2))

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])


In [198]:
print(x.view(2,4))

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


# Store the reshaped tensor otherwise, it won't persist

In [199]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [200]:
y=x.view(2,4)
print(x)
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


## Slicing a tensor 

0 based indexing

In [201]:
print(y)
print(y[0])
print(y[1])

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([0, 1, 2, 3])
tensor([4, 5, 6, 7])


In [202]:
z= y[1:]
print(z)
print('dimension=',z.dim())
print(z.size())

tensor([[4, 5, 6, 7]])
dimension= 2
torch.Size([1, 4])


### Acessing the entries of a Tensor

In [203]:
s = y[1,2]
#  s is a zero-dimensional tensor; to access the scalar use s.item()
print(s) 
print(s.dim())
print(s.size())

tensor(6)
0
torch.Size([])
